from flask_mail import Message
from extensions import mail
from datetime import datetime

def send_dmca_email(report_data):
    """
    Sends a DMCA takedown simulation email to dummy Gmail account.
    In real deployment this would go to platform abuse emails.
    report_data: dict with report details
    """

    # Simulation target — dummy Gmail instead of real platform
    DUMMY_EMAIL = "maria.amir.tech@gmail.com"

    platform = report_data.get('platform', 'Unknown Platform')
    report_id = report_data.get('report_id', 'N/A')
    category = report_data.get('category', 'N/A')
    description = report_data.get('description', 'N/A')
    token = report_data.get('token', 'N/A')
    manipulation_score = report_data.get('manipulation_score', 'N/A')
    verdict = report_data.get('verdict', 'N/A')
    date = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')

    subject = f"[ShieldNet] DMCA Takedown Request — Case #{report_id} — {platform}"

    body = f"""
DMCA TAKEDOWN NOTICE
====================
Sent via ShieldNet — Cyber Harassment Reporting Platform
University of Lahore, IET Department

Date: {date}
Case ID: {report_id}
Tracking Token: {token}

TO: abuse@{platform.lower().replace(' ', '')}.com [SIMULATION]
FROM: ShieldNet Automated Complaint System

---

PLATFORM: {platform}
VIOLATION CATEGORY: {category}
DESCRIPTION:
{description}

---

AI ANALYSIS RESULTS:
Manipulation Score: {manipulation_score}%
Verdict: {verdict}

---

DMCA STATEMENT:
Under the Digital Millennium Copyright Act (DMCA), I hereby formally
request the immediate removal of the content described above from {platform}.

The reported content constitutes cyber harassment and/or unauthorized
use of personal images/content. AI-assisted analysis has verified
manipulation with a score of {manipulation_score}%.

This is a simulation complaint generated by ShieldNet FYP.
In a live deployment, this email would be sent directly to:
abuse@{platform.lower().replace(' ', '')}.com

---

ShieldNet | University of Lahore IET
Supervisor: Sir Abdul Malik
Generated: {date}
"""

    try:
        msg = Message(
            subject=subject,
            sender="shieldnet.dummy@gmail.com",
            recipients=[DUMMY_EMAIL],
            body=body
        )
        mail.send(msg)
        return {'success': True, 'message': f'DMCA email sent to {DUMMY_EMAIL}'}

    except Exception as e:
        return {'success': False, 'error': str(e)}