import socket
socket.setdefaulttimeout(10)
import resend
import os
from datetime import datetime

resend.api_key = os.getenv('RESEND_API_KEY')
def send_dmca_email(report_data):
    DUMMY_EMAIL = "maria.amir.tech@gmail.com"

    platform = report_data.get('platform', 'Unknown Platform')
    report_id = report_data.get('report_id', 'N/A')
    category = report_data.get('category', 'N/A')
    description = report_data.get('description', 'N/A')
    token = report_data.get('token', 'N/A')
    manipulation_score = report_data.get('manipulation_score', 'N/A')
    pixel_difference = report_data.get('pixel_difference', 'N/A')
    verdict = report_data.get('verdict', 'N/A')
    date = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')

    harasser_username = report_data.get('harasser_username', 'Not provided')
    harasser_platform = report_data.get('harasser_platform', 'N/A')
    harasser_report_count = report_data.get('harasser_report_count', 0)
    harasser_flagged = report_data.get('harasser_flagged', False)
    harasser_profile_url = report_data.get('harasser_profile_url')
    profile_link_html = f'<a href="{harasser_profile_url}">{harasser_profile_url}</a>' if harasser_profile_url else 'Not provided'

    subject = f"[ShieldNet] DMCA Takedown Request — Case #{report_id} — {platform}"
    body_html = f"""
    <h2>DMCA TAKEDOWN NOTICE</h2>
    <p>Sent via ShieldNet — Cyber Harassment Reporting Platform<br>
    University of Lahore, IET Department</p>
    <hr>
    <p><b>Date:</b> {date}<br>
    <b>Case ID:</b> {report_id}<br>
    <b>Tracking Token:</b> {token}</p>
    <hr>
    <p><b>PLATFORM:</b> {platform}<br>
    <b>VIOLATION CATEGORY:</b> {category}<br>
    <b>DESCRIPTION:</b><br>{description}</p>
    <hr>
    <p><b>REPORTED HARASSER:</b><br>
    Username/Handle: {harasser_username}<br>
    Profile Link: {profile_link_html}<br>
    Platform: {harasser_platform}<br>
    Total Reports Against This Account: {harasser_report_count}<br>
    Flagged for Repeat Offenses: {'Yes' if harasser_flagged else 'No'}</p>
    <hr>
    <p><b>AI ANALYSIS RESULTS:</b><br>
    Manipulation Score: {manipulation_score}%<br>
    Pixel Difference: {pixel_difference}<br>
    Verdict: {verdict}</p>
    <hr>
    <p>Under the Digital Millennium Copyright Act (DMCA), I hereby formally
    request the immediate removal of the content described above from {platform}.
    The reported content constitutes cyber harassment and/or unauthorized
    use of personal images/content, evidenced by AI-assisted analysis above.</p>
    <p><i>This is a simulation complaint generated by ShieldNet FYP. In a live
    deployment, this would be sent to the platform's official abuse contact
    along with the original evidence images as attachments.</i></p>
    <hr>
    <p>ShieldNet | University of Lahore IET<br>
    Supervisor: Sir Abdul Malik<br>
    Generated: {date}</p>
    """

    try:
        result = resend.Emails.send({
            "from": "ShieldNet <onboarding@resend.dev>",
            "to": [DUMMY_EMAIL],
            "subject": subject,
            "html": body_html
        })
        return {'success': True, 'message': f'DMCA email sent to {DUMMY_EMAIL}', 'id': result.get('id')}
    except Exception as e:
        return {'success': False, 'error': str(e)}